src/main/java/ch/ultrasoft/jsfxsltgui/bean/DemoBean.java
package ch.ultrasoft.jsfxsltgui.bean;

import java.io.Serializable;
import java.math.BigInteger;
import java.security.SecureRandom;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;

import org.apache.log4j.Logger;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.LazyDataModel;

import ch.ultrasoft.jsfxsltgui.model.Dummy;
import ch.ultrasoft.jsfxsltgui.model.LazyDummyDataScrollModel;
import ch.ultrasoft.jsfxsltgui.service.DummyService;

@Named("dummyBean")
@ViewScoped
public class DemoBean implements Serializable {

	private static final long serialVersionUID = -5703244300384213407L;
	private static final Logger LOG = Logger.getLogger(DemoBean.class);

	private Dummy selected = new Dummy();
	private LazyDataModel<Dummy> lazyScrollingModel;
	
	@Inject
	private DummyService service;

	@PostConstruct
	public void init() {
		lazyScrollingModel = service.createLazyDummyDataScrollModel();
	}
	
	public void onRowSelect(SelectEvent event) {
		Dummy d = (Dummy) event.getObject();
		LOG.info(d);
		FacesContext.getCurrentInstance().addMessage(
				"", 
				new FacesMessage("Selected", d.toString()));
	}

	public void createTestDummies(int recordsToCreate) {
		service.createTestDummies(recordsToCreate);
	}
	
	public LazyDataModel<Dummy> getLazyScrollingModel() {
		return lazyScrollingModel;
	}
	
	public void saveSelected() {
		try {
			selected = service.saveDummy(selected);
			FacesContext.getCurrentInstance().addMessage("",new FacesMessage("saved", selected.toString()));
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage("",new FacesMessage(FacesMessage.SEVERITY_ERROR, "save faild", e.getMessage()));
		}
	}
	
	public void create() {
		selected = new Dummy();
	}

	public Dummy getSelected() {
		return selected;
	}

	public void setSelected(Dummy selected) {
		this.selected = selected;
	}

	public long getResultSize() {
		return service.getResultSize();
	}

}

src/main/java/ch/ultrasoft/jsfxsltgui/bean/NavigationBean.java
package ch.ultrasoft.jsfxsltgui.bean;

import java.io.File;
import java.io.Serializable;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.servlet.ServletContext;

@Named("navigationBean")
@ApplicationScoped
public class NavigationBean implements Serializable {

	private static final long serialVersionUID = 6857667633998234386L;
	private String webappRootAbsolute;
	
	@PostConstruct
	public void init() {
		ServletContext ctx = (ServletContext) FacesContext.getCurrentInstance()
	            .getExternalContext().getContext();
		webappRootAbsolute = ctx.getRealPath("/");
	}

	public String resolveCustomXHTMLRelative(String defaultPath) {
		String customFile = defaultPath.replaceAll(".xhtml", "_TEST.xhtml");
		if (new File(webappRootAbsolute + customFile).exists())
			return customFile;
		return defaultPath;
	}

	public String resolveCustomXHTMLAbsolute(String defaultPath) {
		String customFile = defaultPath.replaceAll(".xhtml", "_TEST.xhtml");
		if (new File(webappRootAbsolute + customFile).exists())
			return webappRootAbsolute + customFile;
		return webappRootAbsolute + defaultPath;
	}
	
	public String getWebappRootAbsolute() {
		return webappRootAbsolute;
	}
}

src/main/java/ch/ultrasoft/jsfxsltgui/model/Dummy.java
package ch.ultrasoft.jsfxsltgui.model;

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

@Entity
public class Dummy implements Serializable {

	private static final long serialVersionUID = 4357146545176778618L;

	@Id
	@GeneratedValue
	private Long id;

	private String name;
	
	private String vorname;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getVorname() {
		return vorname;
	}

	public void setVorname(String vorname) {
		this.vorname = vorname;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Dummy other = (Dummy) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Dummy [id=" + id + ", name=" + name + "]";
	}
}

src/main/java/ch/ultrasoft/jsfxsltgui/model/LazyDummyDataScrollModel.java
package ch.ultrasoft.jsfxsltgui.model;

import java.util.Iterator;
import java.util.List;
import java.util.Map;

import javax.persistence.EntityManager;
import javax.persistence.Query;

import org.apache.log4j.Logger;
import org.primefaces.model.LazyDataModel;
import org.primefaces.model.SortOrder;

public class LazyDummyDataScrollModel extends LazyDataModel<Dummy> {

	private static final long serialVersionUID = 789L;
	private static final Logger LOG = Logger.getLogger(LazyDummyDataScrollModel.class);

	private EntityManager em;

	public LazyDummyDataScrollModel(EntityManager em) {
		this.em = em;
	}

	@Override
	public Dummy getRowData(String rowKey) {
		return em.find(Dummy.class, Long.valueOf(rowKey));
	}

	@Override
	public Object getRowKey(Dummy car) {
		return car.getId();
	}

	@Override
	public List<Dummy> load(int first, int pageSize, String sortField, SortOrder sortOrder,
			Map<String, Object> filters) {

		Query query = createQuery(first, pageSize, sortField, sortOrder, filters);
		this.setRowCount(query.getMaxResults());
		List<Dummy> resultList = query.setFirstResult(first).setMaxResults(pageSize).getResultList();
		
		LOG.info("resultList.size(): " + resultList.size());
		return resultList; 
	}

	private Query createQuery(int first, int pageSize, String sortField, SortOrder sortOrder,
			Map<String, Object> filters) {
		Query query = null;
		String hql = "FROM Dummy d \n/*FILTER*/ \n/*ORDER_BY*/";
		// sort
		hql = appendOrderBy(sortField, sortOrder, hql);
		// filter
		hql = appendFilter(filters, hql);

		query = em.createQuery(hql);
		putParametersToQuery(filters, query);

		LOG.info(String.format("\nHQL: %s\nfirstResult: %s\nmaxResult: %s", hql, first, pageSize));
		return query;
	}

	private String appendFilter(Map<String, Object> filters, String hql) {
		if (filters != null && !filters.isEmpty()) {
			String hqlFilter = "";
			boolean first = true;
			for (Iterator<String> it = filters.keySet().iterator(); it.hasNext();) {
				String filterProperty = it.next();
				hqlFilter += first ? "WHERE " : "\n\tAND ";
//				if (filterProperty.equals("globalFilter"))
//					hqlFilter += "d.name LIKE :name";
//				else
				hqlFilter += String.format("d. %s LIKE :%s", filterProperty, filterProperty);
				first = false;
			}
			return hql.replaceAll("/\\*FILTER\\*/", hqlFilter);
		} else {
			return hql.replaceAll("\\s/\\*FILTER\\*/", "");
		}
	}

	private String appendOrderBy(String sortField, SortOrder sortOrder, String hql) {
		if (sortField != null && sortOrder != null) {
			return hql.replaceAll("/\\*ORDER_BY\\*/", String.format("ORDER BY d.%s %s", sortField,
					(sortOrder.equals(SortOrder.DESCENDING) ? "DESC" : "ASC")));
		} else {
			return hql.replaceAll("\\s/\\*ORDER_BY\\*/", "");
		}
	}

	private void putParametersToQuery(Map<String, Object> filters, Query query) {
		if (filters != null && !filters.isEmpty()) {
			for (Iterator<String> it = filters.keySet().iterator(); it.hasNext();) {
				String filterProperty = it.next();
				Object filterValue = filters.get(filterProperty);
				if (LOG.isDebugEnabled())
					LOG.debug(String.format("%s : %s", filterProperty, filterValue));
//				if (filterProperty.equals("globalFilter"))
//					query.setParameter("name", String.format("%%%s%%", filterValue));
				else
					query.setParameter(filterProperty, String.format("%%%s%%", filterValue));
			}
		}
	}

}

src/main/java/ch/ultrasoft/jsfxsltgui/view/model/JSFViewComponent.java
package ch.ultrasoft.jsfxsltgui.view.model;

import java.util.ArrayList;
import java.util.List;

public class JSFViewComponent {
	private String id = null;
	private List<JSFViewComponentAttribute> attributes = null;

	public JSFViewComponent(String id, List<JSFViewComponentAttribute> attributes) {
		this.id = id;
		this.attributes = attributes;
	}
	
	public JSFViewComponent(String id) {
		this(id, new ArrayList<JSFViewComponentAttribute>());
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<JSFViewComponentAttribute> getAttributes() {
		return attributes;
	}

	public void setAttributes(List<JSFViewComponentAttribute> attributes) {
		this.attributes = attributes;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		JSFViewComponent other = (JSFViewComponent) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}

src/main/java/ch/ultrasoft/jsfxsltgui/view/model/JSFViewComponentAttribute.java
package ch.ultrasoft.jsfxsltgui.view.model;

public class JSFViewComponentAttribute {
	private String id = null;
	private String value = null;

	public JSFViewComponentAttribute(String id, String value) {
		this.id = id;
		this.value = value;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((value == null) ? 0 : value.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		JSFViewComponentAttribute other = (JSFViewComponentAttribute) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (value == null) {
			if (other.value != null)
				return false;
		} else if (!value.equals(other.value))
			return false;
		return true;
	}
	
	
}

src/main/java/ch/ultrasoft/jsfxsltgui/view/model/JSFViewComponentList.java
package ch.ultrasoft.jsfxsltgui.view.model;

import java.util.ArrayList;
import java.util.List;

public class JSFViewComponentList {
	private String id = null;
	private List<JSFViewComponent> jsfViewComponents = null;

	public JSFViewComponentList(String id, List<JSFViewComponent> jsfViewComponent) {
		this.id = id;
		this.jsfViewComponents = jsfViewComponent;
	}
	
	public JSFViewComponentList(String id) {
		this(id, new ArrayList<JSFViewComponent>());
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public List<JSFViewComponent> getJsfViewComponents() {
		return jsfViewComponents;
	}

	public void setJsfViewComponents(List<JSFViewComponent> jsfViewComponent) {
		this.jsfViewComponents = jsfViewComponent;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((jsfViewComponents == null) ? 0 : jsfViewComponents.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		JSFViewComponentList other = (JSFViewComponentList) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (jsfViewComponents == null) {
			if (other.jsfViewComponents != null)
				return false;
		} else if (!jsfViewComponents.equals(other.jsfViewComponents))
			return false;
		return true;
	}
}

src/main/java/ch/ultrasoft/jsfxsltgui/service/ViewEditorServlet.java
package ch.ultrasoft.jsfxsltgui.service;

import java.io.FileWriter;
import java.io.IOException;

import javax.inject.Inject;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactoryConfigurationError;

import org.apache.log4j.Logger;

import ch.ultrasoft.jsfxsltgui.bean.NavigationBean;
import ch.ultrasoft.jsfxsltgui.transformer.XSLTransformer;
import ch.ultrasoft.jsfxsltgui.view.model.JSFViewComponentAttribute;
import ch.ultrasoft.jsfxsltgui.view.model.JSFViewComponentList;
import ch.ultrasoft.jsfxsltgui.view.model.utils.JSFViewModelUtils;

@WebServlet("/ViewEditorServlet")
public class ViewEditorServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
	private static final Logger LOG = Logger.getLogger(ViewEditorServlet.class);
	private final String XHTML = "resources/jsf/fragments/fields/dummyFields.xhtml"; // = getServletContext().getRealPath("resources/jsf/fragments/fields/dummyFields.xhtml"); //"src/test/resources/dummyFields.xhtml";
	private static final String PRAEFIX = "TEST";
	
	private JSFViewComponentList jSFViewComponents = null;
	private XSLTransformer xslTransformer = new XSLTransformer();

	@Inject
	private NavigationBean navigationBean;
	
    public ViewEditorServlet() {
        super();
        jSFViewComponents = new JSFViewComponentList(XHTML);
    }
    
    @Override
    protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
    	try {
    		String absolutePathToXHTML = navigationBean.resolveCustomXHTMLAbsolute(XHTML);
			String html = xslTransformer.fromXHTML(absolutePathToXHTML, jSFViewComponents).toString();
			String toXhtml = xslTransformer.toXHTML(absolutePathToXHTML, jSFViewComponents).toString();
			toXhtml = toXhtml.replaceAll("<", "&lt;").replaceAll(">", "&gt;");
			if (toXhtml != null && !toXhtml.isEmpty()) {
				html = html.replaceAll("toXHTML.xsl", toXhtml);
				resp.getWriter().append(html);
			}
			LOG.debug(html);
		} catch (TransformerFactoryConfigurationError | TransformerException e) {
			LOG.error("error XSLTransformer().fromXHTML: " + getServletContext().getRealPath(XHTML), e);
		}
    }
    
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String page = request.getParameter("page");
		String name = request.getParameter("name");
		String value = request.getParameter("value");
		String componentId = request.getParameter("componentId");
		String saveXHTML = request.getParameter("saveXHTML");

		LOG.info(name);
		LOG.info(value);
		LOG.info(page);
		LOG.info(componentId);
		
		if (saveXHTML != null && !saveXHTML.isEmpty()) {
			try {
				String path = navigationBean.getWebappRootAbsolute() + XHTML.replace(".xhtml", "_TEST.xhtml");
				String xhtml = xslTransformer.toXHTML(navigationBean.resolveCustomXHTMLAbsolute(XHTML), jSFViewComponents).toString();
				writeXHTML(path, xhtml);
			} catch (TransformerFactoryConfigurationError | TransformerException e) {
				LOG.error("", e);
			}
		} else {
			JSFViewComponentAttribute attribute = new JSFViewComponentAttribute(name, value); 
			JSFViewModelUtils.addAttribute(jSFViewComponents, attribute, componentId);
		}
		doGet(request, response);
	}
	
	private void writeXHTML(String path, String xhtml) {
		try (FileWriter fileWriter = new FileWriter(path);) {
			fileWriter.write(xhtml);
			fileWriter.flush();
		} catch (IOException e) {
			LOG.error("writeXHTML", e);
		}
	}
}

src/main/webapp/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui">

<h:head>

</h:head>
<h:body>

<style>
</style>
	<p:growl 
		id="growl" 
		sticky="false"
		life="3000"
		autoUpdate="false"
		showDetail="true" />
	
	
	<h:form id="mainForm">
		<p:toolbar>
	        <f:facet name="left">
				<p:commandButton
					value="GuiEditor"
					onclick="location.replace('ViewEditorServlet');"/>
			</f:facet>
		</p:toolbar>
		
		<p:panelGrid 
			columns="1" 
			style="margin: auto;"
			styleClass="ui-noborder">
			
			<h:outputText 
				value="Dummy data" 
				style="font-size:36px;" />
		</p:panelGrid>
			
		<p:panelGrid 
			columns="2" 
			id="grid" 
			style="margin: auto;"
			styleClass="ui-noborder">
		
			<h:outputText 
				value="Result Size" />
			
			<p:inputNumber
				disabled="true"
				thousandSeparator="'"
				decimalPlaces="0" 
				value="#{dummyBean.resultSize}" />
	
			<p:commandButton 
				onclick="PF('dialog').show();" 
				icon="ui-icon-check"
				value="show Dummies"
				update=":dialogForm"
				immediate="true"
				partialSubmit="true"/>
			
			<p:commandButton 
				actionListener="#{dummyBean.createTestDummies(10000)}"
				update="grid"
				icon="ui-icon-plus"
				value="create 10'000 dummies"
				immediate="true"
				process="@this"
				onclick="PF('blockAll').show()"
				oncomplete="PF('blockAll').hide()"
				partialSubmit="true"/>
		</p:panelGrid>
	</h:form>

	<p:dialog 
		widgetVar="blockAll"
		closable="false"
		modal="true"
		resizable="false"
		appendTo="@(body)"
		header="loading...">
		
		<p:panelGrid 
			columns="1" 
			style="width:100%;text-align:center;"
			styleClass="ui-noborder">
			
			<p:graphicImage 
				value="resources/images/loader.gif" />

		</p:panelGrid>
	</p:dialog>
			
	<p:dialog
		dynamic="true" 
		width="500"
		widgetVar="dialog"
		id="dialog"
		draggable="false"
		modal="true"
		appendTo="@(body)"
		header="Dummies">
		
		<h:form 
			id="dialogForm"
			rendered="true">
			<p:commandButton
				style="width:100%;" 
				actionListener="#{dummyBean.create()}"
				update=":dialogUpdate"
				icon="ui-icon-plus"
				value="create new dummy"
				immediate="true"
				process="@this"
				oncomplete="PF('dialogUpdate').show();"
				partialSubmit="true"/>		
				
			<p:dataTable
				widgetVar="dummyTable"
				id="dummyTable" 
				var="r" 
				value="#{dummyBean.lazyScrollingModel}" 
				scrollRows="20" 
				scrollable="true" 
				liveScroll="true" 
				scrollHeight="200" 
				lazy="true" 
				rows="40"
				selectionMode="single" 
				selection="#{dummyBean.selected}"
				rowKey="#{r.id}">
				
				<p:ajax 
					event="rowSelect"
					immediate="true"
					async="true"
					partialSubmit="true" 
					listener="#{dummyBean.onRowSelect}"
					oncomplete="PF('dialogUpdate').show();"
					update="growl :dialogUpdate" />
				<p:ajax 
					event="sort" 
					immediate="true"
					onstart="PF('blockAll').show();"
					oncomplete="PF('blockAll').hide();" />
				<p:ajax 
					event="filter" 
					immediate="true"
					onstart="PF('blockAll').show();"
					oncomplete="PF('blockAll').hide();" />
				<p:ajax 
					event="page" 
					immediate="true"
					onstart="PF('blockAll').show();"
					oncomplete="PF('blockAll').hide();" />
				<!-- <f:facet name="header">
		            <p:outputPanel>
		                <h:outputText value="Search all fields:" />
		                <p:inputText id="globalFilter" onkeyup="PF('dummyTable').filter()" style="width:150px" placeholder="Enter keyword"/>
		            </p:outputPanel>
		        </f:facet> -->
	        	<p:column 
	        		sortable="true"
	        		sortBy="#{id}"
	        		width="60">
	        		<h:outputText value="#{r.id}" />
	        	</p:column>
	        	
	        	<p:column 
	        		sortable="true"
	        		sortBy="#{name}"
	        		filterable="true"
	        		filterBy="#{name}"
	        		filterStyle="width: 100%;"
	        		filterPosition="top"
	        		filterMatchMode="contains">
	        		<h:outputText value="#{r.name}" />
	        	</p:column>
	
			</p:dataTable>
		</h:form>
	</p:dialog>
	
	<p:dialog
		dynamic="true"
		width="500"
		widgetVar="dialogUpdate"
		id="dialogUpdate"
		draggable="false"
		modal="true"
		appendTo="@(body)"
		header="edit">
		<h:form>
			<h:outputLabel value="#{navigationBean.resolveCustomXHTMLRelative('resources/jsf/fragments/fields/dummyFields.xhtml')}" />
			<ui:include src="#{navigationBean.resolveCustomXHTMLRelative('resources/jsf/fragments/fields/dummyFields.xhtml')}"></ui:include>
	
			<p:panelGrid columns="2" style="text-align:center;width:100%;">
			<p:commandButton 
					icon="ui-icon-disk"
					update=":growl :dialogForm:dummyTable :mainForm:grid"
					validateClient="true"
					actionListener="#{dummyBean.saveSelected()}"
					oncomplete="if (args &amp;&amp; !args.validationFailed) PF('dialogUpdate').hide();"/>
				
				<p:commandButton 
					icon="ui-icon-remove"
					immediate="true" 
					update=":mainForm:grid"
					onclick="PF('dialogUpdate').hide();"/>
			</p:panelGrid>
		</h:form>
	</p:dialog>
</h:body>
</html>